# Generated by Django 2.1 on 2019-03-17 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='key',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='video_id',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
