# Generated by Django 2.1 on 2019-03-17 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20190317_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='key',
            field=models.CharField(default='happy', max_length=50),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_id',
            field=models.CharField(default='M7lc1UVf-VE', max_length=50),
        ),
    ]
