# Generated by Django 2.1 on 2019-03-22 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_video_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='video_id',
            new_name='url',
        ),
        migrations.RemoveField(
            model_name='video',
            name='file',
        ),
    ]
