# Generated by Django 2.1 on 2019-03-23 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_auto_20190322_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.CharField(default='M7lc1UVf-VE', max_length=1000),
        ),
    ]
